"""Generate independently loaded study pages from the canonical Potencia content."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUBJECT = ROOT / 'subjects' / 'eletronica-potencia'
SOURCE = (SUBJECT / 'content.html').read_text(encoding='utf-8')
SECTIONS = {m[1]: m[0] for m in re.finditer(
    r'^      <section id="([^"]+)".*?^      </section>', SOURCE, re.M | re.S)}
EXTRAS = SOURCE[SOURCE.index('      <button id="examFormulaFab"'):SOURCE.index('      <!-- RODAPÉ TÉCNICO -->')]
FOOTER = SOURCE[SOURCE.index('      <!-- RODAPÉ TÉCNICO -->'):]
PAGES = []
OUTPUTS = {}


def url(page):
    return 'guide.html?subject=eletronica-potencia&amp;page=' + page


def tabs(items, selected, label):
    links = []
    for page, title in items:
        active = page == selected
        links.append(f'<a id="tab-{page}" role="tab" aria-selected="{str(active).lower()}" '
                     f'tabindex="{0 if active else -1}" aria-controls="topicPanel" href="{url(page)}">{title}</a>')
    return f'<nav class="topic-tabs" role="tablist" aria-label="{label}">' + ''.join(links) + '</nav>'


def section(ident, title, body, description='', tag='Prática'):
    return (f'<section id="{ident}" class="module-section"><div class="module-header">'
            f'<div class="module-header-left"><span class="module-tag">{tag}</span>'
            f'<h2 class="module-title">{title}</h2><p class="module-desc">{description}</p></div></div>'
            f'<div class="module-body">{body}</div></section>')


def add(page, title, markup, nav_anchor=None, tab_markup='', selected=None):
    anchors = [anchor for anchor in re.findall(r'(?<![\w-])id="([^"]+)"', markup)
               if not anchor.startswith('dashboard-host-')]
    if selected:
        markup = (tab_markup + f'<div id="topicPanel" role="tabpanel" aria-labelledby="tab-{selected}">'
                  + markup + '</div>')
    path = 'pages/' + page + '.html'
    OUTPUTS[path] = '<!-- Generated by scripts/build-topic-pages.py; edit content.html for source content. -->\n' + markup + '\n' + EXTRAS + FOOTER
    entry = {'id': page, 'file': path, 'title': title, 'navAnchor': nav_anchor or (anchors[0] if anchors else ''), 'anchors': anchors}
    if page.startswith('revisao'): entry['preloadGroup'] = 'review'
    PAGES.append(entry)


hero = re.search(r'^      <section class="hero-banner">.*?^      </section>', SOURCE, re.M | re.S)[0]
intro = ('<div class="topic-overview"><h3>Escolha o que estudar</h3>'
         '<p>Cada tópico abre uma página própria. Na revisão, escolha a topologia e depois CCM ou DCM.</p>'
         '<div class="topic-card-grid">'
         f'<a href="{url("mod1")}"><strong>Teoria e exercícios</strong><span>Nove módulos, um por página.</span></a>'
         f'<a href="{url("revisao")}"><strong>Revisão por topologia</strong><span>Buck, Boost e Buck-Boost; CCM e DCM.</span></a>'
         f'<a href="{url("historico")}"><strong>Provas anteriores</strong><span>Análise histórica e quatro provas resolvidas.</span></a>'
         f'<a href="{url("simulado-a")}"><strong>Simulados e projetos</strong><span>Escolha um conjunto para praticar.</span></a>'
         '</div></div>')
add('inicio', 'Visão geral', hero + intro)
for i in range(1, 10):
    markup = SECTIONS[f'mod{i}']
    title = re.search(r'<h2 class="module-title">(.*?)</h2>', markup)[1]
    add(f'mod{i}', title, markup, f'mod{i}')

review = SECTIONS['waveformReviewSection']
table = re.search(r'<div class="table-wrapper"><table class="content-table">.*?</table></div>', review, re.S)[0]
for topology, name, ccm, dcm in [('buck', 'Buck', 4, 7), ('boost', 'Boost', 5, 8), ('buckboost', 'Buck-Boost', 6, 9)]:
    for mode, module in [('CCM', ccm), ('DCM', dcm)]:
        page = 'revisao' if module == 4 else f'revisao-{topology}-{mode.lower()}'
        ident = 'waveformReviewSection' if module == 4 else f'review-{topology}-{mode.lower()}'
        top_items = [(('revisao' if t == 'buck' and mode == 'CCM' else f'revisao-{t}-{mode.lower()}'), n)
                     for t, n in [('buck', 'Buck'), ('boost', 'Boost'), ('buckboost', 'Buck-Boost')]]
        top_items.append(('revisao-roteiro', 'Roteiro e balanços'))
        mode_items = [(('revisao' if topology == 'buck' and m == 'CCM' else f'revisao-{topology}-{m.lower()}'), m) for m in ['CCM', 'DCM']]
        # Topology and mode controls have distinct DOM IDs even when their links point to the same page.
        top_tabs = tabs(top_items, page, 'Topologia').replace('id="tab-', 'id="topology-').replace('aria-controls="topicPanel"', 'aria-controls="modeTabs"')
        mode_tabs = tabs(mode_items, page, 'Regime de condução').replace('class="topic-tabs"', 'id="modeTabs" class="topic-tabs topic-subtabs"')
        label = 'Inversor' if topology == 'buckboost' else name
        rows = re.findall(r'<tr><td>' + label + r' • .*?</tr>', table, re.S)
        if mode == 'CCM': rows = rows[:2]
        head = re.search(r'<thead>.*?</thead>', table, re.S)[0]
        stages = '<div class="table-wrapper"><table class="content-table">' + head + '<tbody>' + ''.join(rows) + '</tbody></table></div>'
        body = (f'<div id="dashboard-host-mod{module}" class="converter-dashboard-slot"></div>'
                f'<details class="topic-details"><summary>Tensões e correntes por etapa — {name} {mode}</summary>'
                '<p>E = Vin, V = |vout|. vD = vA − vK; iC entra no terminal positivo de C.</p>' + stages +
                '<p>ON dura DTs; o diodo conduz por D₂Ts. Em CCM, D₂ = 1 − D. Em DCM, D₃ = 1 − D − D₂ &gt; 0.</p></details>'
                f'<p><a class="topic-link" href="#mod{module}">Abrir teoria, equações e exercícios de {name} {mode}</a></p>')
        markup = section(ident, f'{name} em {mode}', body,
            'Inspecione os estados e alterne os gráficos de L, semicondutores e capacitor.', 'Revisão por topologia')
        markup = markup.replace('class="module-section"', 'class="module-section topology-review"', 1)
        add(page, f'Revisão • {name} {mode}', markup,
            'waveformReviewSection', top_tabs + mode_tabs, page)

general_tabs = tabs([('revisao', 'Buck'), ('revisao-boost-ccm', 'Boost'), ('revisao-buckboost-ccm', 'Buck-Boost'), ('revisao-roteiro', 'Roteiro e balanços')], 'revisao-roteiro', 'Topologia')
add('revisao-roteiro', 'Roteiro de formas de onda e balanços', review.replace('id="waveformReviewSection"', 'id="reviewWorkflowSection"'),
    'waveformReviewSection', general_tabs, 'revisao-roteiro')
formulas = SECTIONS['cheatSheetSection'].replace('<div class="module-body">',
    '<div class="module-body"><p>Para circuitos, formas de onda e extremos de corrente/tensão, '
    '<a href="#waveformReviewSection">abra a revisão por topologia</a>.</p>', 1)
add('formulas', 'Fórmulas para a P1', formulas, 'cheatSheetSection')
add('calculadora', 'Calculadora de conversores', SECTIONS['calculatorSection'], 'calculatorSection')

history = SECTIONS['historySection']
papers = list(re.finditer(r'^          <article id="([^"]+)".*?^          </article>', history, re.M | re.S))
history_tabs = [('historico', 'Análise histórica'), ('p1-2024', 'Nov/2024'), ('p1-2025-maio', 'Mai/2025'), ('p1-2025-setembro', 'Set/2025'), ('p1-2026', 'Abr/2026')]
overview = re.sub(r'^          <article id="[^"]+".*?^          </article>', '', history, flags=re.M | re.S)
overview = overview.replace('Os gráficos abaixo reconstroem', 'Nas abas de cada prova, os gráficos reconstroem').replace('Abra cada resolução', 'Escolha uma prova e abra cada resolução')
add('historico', 'Provas anteriores • análise histórica', overview, 'historySection', tabs(history_tabs, 'historico', 'Provas anteriores'), 'historico')
for paper in papers:
    title = re.search(r'<span>P1 • ([^<]+)</span>', paper[0])[1]
    # The paper carries its own heading, as on the photographed exam sheet.
    add(paper[1], 'P1 • ' + title,
        '<section id="' + paper[1] + '-page" class="exam-page">' + paper[0] + '</section>',
        'historySection', tabs(history_tabs, paper[1], 'Provas anteriores'), paper[1])

exam = SECTIONS['examSection']
exercises = re.findall(r'^          <div class="exercise-box">.*?^          </div>', exam, re.M | re.S)
assert len(exercises) == 10
practice_tabs = [('simulado-a', 'Simulado A'), ('simulado-b', 'Simulado B'), ('projeto-buck', 'Projetos'), ('fundamentos', 'Fundamentos')]
for page, label, ident, subset in [('simulado-a', 'Simulado A — padrão histórico', 'examSection', exercises[:3]),
                                   ('simulado-b', 'Simulado B — variações de gráficos', 'mockB', exercises[3:6])]:
    alias = '<span id="mockA"></span>' if page == 'simulado-a' else ''
    add(page, label, section(ident, label, alias + '<p>Reserve 45–60 minutos e abra as resoluções depois de tentar.</p>' + '\n'.join(subset),
        'Três questões autorais inspiradas no padrão das provas.'), 'examSection', tabs(practice_tabs, page, 'Prática'), page)
projects = [('projeto-buck', 'Buck CCM'), ('projeto-boost', 'Boost DCM'), ('projeto-buckboost', 'Buck-Boost DCM')]
for index, (page, label) in enumerate(projects):
    ident = 'quizSection' if index == 0 else page + '-section'
    primary = tabs(practice_tabs, 'projeto-buck', 'Prática').replace('id="tab-', 'id="practice-').replace('aria-controls="topicPanel"', 'aria-controls="projectTabs"')
    secondary = tabs(projects, page, 'Projeto de conversor').replace('class="topic-tabs"', 'id="projectTabs" class="topic-tabs topic-subtabs"')
    add(page, 'Projeto • ' + label, section(ident, 'Dimensionamento • ' + label, exercises[6 + index], 'Um projeto por página, com resolução e gráficos.'),
        'examSection', primary + secondary, page)
add('fundamentos', 'Fundamentos complementares', section('fundamentalsPractice', 'Fundamentos complementares', exercises[9],
    'Média, RMS, potência e SCR.'), 'examSection', tabs(practice_tabs, 'fundamentos', 'Prática'), 'fundamentos')

manifest_path = SUBJECT / 'subject.json'
manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
manifest['pages'] = PAGES
manifest['checklistIds'] = re.findall(r'data-check-id="([^"]+)"', SOURCE)
manifest['totalChecklistItems'] = len(manifest['checklistIds'])
manifest['tools'][0]['title'] = 'Revisão por topologia'
manifest['script'] = 'subject.js?v=20260930-provas'
OUTPUTS['subject.json'] = json.dumps(manifest, ensure_ascii=False, indent=2) + '\n'

if __name__ == '__main__':
    args = argparse.ArgumentParser()
    args.add_argument('--check', action='store_true', help='Fail if generated files are stale')
    check = args.parse_args().check
    stale = []
    for relative, contents in OUTPUTS.items():
        path = SUBJECT / relative
        if check:
            if not path.exists() or path.read_text(encoding='utf-8') != contents: stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding='utf-8')
    if stale: raise SystemExit('Stale pages: ' + ', '.join(stale))
    print(f'{len(PAGES)} topic pages; {len(manifest["checklistIds"])} checklist items; generation verified.' if check else f'Generated {len(PAGES)} topic pages.')
